version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    command: dotnet watch
    ports:
      - 8000:8000
    volumes:
      - .:/src
    networks:
      - internal
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    command: bash -c "yarn && yarn dev"
    ports:
      - 8080:3000
    volumes:
      - ./frontend:/frontend
      - ./static:/static:rw
      - node_modules:/frontend/node_modules
    depends_on:
      - db
    environment:
      NODE_PATH: /frontend/node_modules
networks:
  internal:

volumes:
  node_modules:
